### ISSUE TITLE
Can't launch some GUI applications

### ISSUE THREAD

**Issue by xxxifan** [rofl0r/proxychains-ng#119]
I found that if I run proxychains with some GUI applications it can't launch, like chrome, visual-studio-code, etc. but proxychains 3 can do. no log out put for error, it just hang there.

**Comment by rofl0r** [comment]
does that also happen when you disable proxy_dns ?

**Comment by xxxifan** [comment]
yes, I disabled proxy_dns and it can't launch either

**Comment by ikzk** [comment]
I can confirm that netease-cloud-music, opera, chromium also do not work.

**Comment by rofl0r** [comment]
would be helpful to see a backtrace of the "hanging"
(attach to running process with gdb, hit ctrl-c and print a backtrace with 'bt' command)

**Comment by ikzk** [comment]
@rofl0r I never used gdb, so I am not sure whether I am doing it right.
I executed `proxychains4 chromium` and then use `gdb -p` to attach to it. Then hit C-c for chromium and finally `bt` command gives me:

~~~
(gdb) bt
#0  0x00007f1bcbe597ed in nanosleep () from /usr/lib/libpthread.so.0
#1  0x000055c5dc7ddb23 in base::internal::SpinLockDelay(int volatile*, int, int) ()
#2  0x000055c5dc7dd9b4 in SpinLock::SlowLock() ()
#3  0x000055c5dc7d8495 in tcmalloc::ThreadCache::InitModule() ()
#4  0x000055c5e189fe75 in tc_calloc ()
#5  0x00007f1bd1ef4b42 in allocate_dtv () from /lib64/ld-linux-x86-64.so.2
#6  0x00007f1bd1ef54ce in _dl_allocate_tls () from /lib64/ld-linux-x86-64.so.2
#7  0x00007f1bcbe51009 in pthread_create@@GLIBC_2.2.5 () from /usr/lib/libpthread.so.0
#8  0x00007f1bd1c98fbc in ?? () from /usr/lib/libproxychains4.so
#9  0x00007f1bcbe57689 in __pthread_once_slow () from /usr/lib/libpthread.so.0
#10 0x00007f1bd1c982a6 in close () from /usr/lib/libproxychains4.so
#11 0x000055c5dc7e9139 in MmapSysAllocator::Alloc(unsigned long, unsigned long*, unsigned long) ()
#12 0x000055c5dc7e8c46 in DefaultSysAllocator::Alloc(unsigned long, unsigned long*, unsigned long) ()
#13 0x000055c5dc7e936b in TCMalloc_SystemAlloc(unsigned long, unsigned long*, unsigned long) ()
#14 0x000055c5dc7e0ff9 in tcmalloc::MetaDataAlloc(unsigned long) ()
#15 0x000055c5dc7e72f3 in tcmalloc::Static::InitStaticVars() ()
#16 0x000055c5dc7d84d5 in tcmalloc::ThreadCache::InitModule() ()
#17 0x000055c5e189cc65 in tc_malloc ()
#18 0x00007f1bca2969d8 in set_binding_values.part () from /usr/lib/libc.so.6
#19 0x00007f1bca296c9c in bindtextdomain () from /usr/lib/libc.so.6
#20 0x00007f1bc29a9e47 in ?? () from /usr/lib/libgpg-error.so.0
#21 0x00007f1bd1ef24aa in call_init.part () from /lib64/ld-linux-x86-64.so.2
#22 0x00007f1bd1ef25bb in _dl_init () from /lib64/ld-linux-x86-64.so.2
#23 0x00007f1bd1ee3dca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#24 0x0000000000000003 in ?? ()
#25 0x00007fff50e3520b in ?? ()
#26 0x00007fff50e35226 in ?? ()
#27 0x00007fff50e35263 in ?? ()
#28 0x0000000000000000 in ?? ()
~~~

**Comment by rofl0r** [comment]
thanks, this is exactly what was needed.
please report if the fix i committed does indeed resolve the issue.

**Comment by ikzk** [comment]
It still does not work, but the backtrace becomes
~~~
(gdb) bt
#0  0x00007f5dd93697d0 in __nanosleep_nocancel () from /usr/lib/libpthread.so.0
#1  0x000055e253bf0b23 in base::internal::SpinLockDelay(int volatile*, int, int) ()
#2  0x000055e253bf09b4 in SpinLock::SlowLock() ()
#3  0x000055e253beb495 in tcmalloc::ThreadCache::InitModule() ()
#4  0x000055e258cb2e75 in tc_calloc ()
#5  0x00007f5dded9861f in ?? () from /usr/lib/libdl.so.2
#6  0x00007f5dded98088 in dlsym () from /usr/lib/libdl.so.2
#7  0x00007f5ddf1a80db in ?? () from /usr/lib/libproxychains4.so
#8  0x00007f5ddf1a81ab in close () from /usr/lib/libproxychains4.so
#9  0x000055e253bfc139 in MmapSysAllocator::Alloc(unsigned long, unsigned long*, unsigned long) ()
#10 0x000055e253bfbc46 in DefaultSysAllocator::Alloc(unsigned long, unsigned long*, unsigned long) ()
#11 0x000055e253bfc36b in TCMalloc_SystemAlloc(unsigned long, unsigned long*, unsigned long) ()
#12 0x000055e253bf3ff9 in tcmalloc::MetaDataAlloc(unsigned long) ()
#13 0x000055e253bfa2f3 in tcmalloc::Static::InitStaticVars() ()
#14 0x000055e253beb4d5 in tcmalloc::ThreadCache::InitModule() ()
#15 0x000055e258cafc65 in tc_malloc ()
#16 0x00007f5dd77a69d8 in set_binding_values.part () from /usr/lib/libc.so.6
#17 0x00007f5dd77a6c9c in bindtextdomain () from /usr/lib/libc.so.6
#18 0x00007f5dcfeb7e47 in ?? () from /usr/lib/libgpg-error.so.0
#19 0x00007f5ddf4024aa in call_init.part () from /lib64/ld-linux-x86-64.so.2
#20 0x00007f5ddf4025bb in _dl_init () from /lib64/ld-linux-x86-64.so.2
---Type <return> to continue, or q <return> to quit---
#21 0x00007f5ddf3f3dca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#22 0x0000000000000003 in ?? ()
#23 0x00007ffe6397f204 in ?? ()
#24 0x00007ffe6397f21f in ?? ()
#25 0x00007ffe6397f25c in ?? ()
#
~~~

**Comment by rofl0r** [comment]
if you can try another time...

**Comment by ikzk** [comment]
@rofl0r I can successfully launch these GUI applications now!

Thanks a lot for your work!

**Comment by rofl0r** [comment]
nice, thanks for testing and the backtraces

**Comment by yi-ji** [comment]
@ikzk Hi there, I am happy to find out that you were doing the same thing (using proxychains for Netease Music) with me. 

I am still stuck in the same situation as described in https://github.com/rofl0r/proxychains-ng/issues/181, so could you kindly shared more info about how you fixed this problem finally? That would be greatly helpful for me🙏

**Comment by ikzk** [comment]
@yi-ji I just used the fixed master branch and it worked.

**Comment by yi-ji** [comment]
Okay I just realized you are using NeteaseMusic for Linux...different thing then
